#+TITLE: dotfiles
A masterpiece in progress.

* Legacy
  My older dotfiles can be found on the =legacy= branch. They offer
  more/different configurations than the =master= branch, but are no longer
  updated and may be removed whenever I see fit.

* Installation
  Information on how to install the set of dotfiles. I'm running Arch Linux on a
  Lenovo Thinkpad T450s.
** i3-gaps
   I use =i3-gaps= as my Window Manager. It can be obtained from the AUR.
*** x
    Like most (maybe all?) Window Manager/Desktop Environments, =i3= runs on an
    =x= server.
    
    #+BEGIN_SRC sh
    $ sudo pacman -S xorg-server xorg-xinit
    #+END_SRC
*** i3blocks
    I use =i3blocks= to customize my =i3bar=. It can be obtained from the AUR.
** stow
   I use =stow= to manage most of my dotfiles. It can be obtained from the Arch
   official repositories.

   #+BEGIN_SRC sh
   $ sudo pacman -S stow
   #+END_SRC
** emacs
   I use =emacs= for my "editor". It can be obtained from the official Arch
   repositories. 
   
   #+BEGIN_SRC sh
   $ sudo pacman -S emacs
   #+END_SRC
** vimfx
   I use Firefox's add-on, =vimfx=, to get around the internet. It can obtained
   within Firefox.
** zsh
   I use =zsh= for my shell. It can be obtained from the official Arch
   repositories.

   #+BEGIN_SRC sh
   $ sudo pacman -S zsh
   #+END_SRC
