#! /bin/sh
bspc monitor -d a b c d e

bspc config border_width        2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a Emacs state=tiled
