const LEFT = 'd';
const RIGHT = 'n';
const DOWN = 'h';
const UP = 't';

vimfx.set('mode.normal.focus_location_bar', 'o');
vimfx.set('mode.normal.focus_search_bar', 'O');
vimfx.set('mode.normal.history_back', 'e');
vimfx.set('mode.normal.history_forward', 'u');
vimfx.set('mode.normal.reload', 'r');
vimfx.set('mode.normal.scroll_up', UP);
vimfx.set('mode.normal.scroll_down', DOWN);
vimfx.set('mode.normal.scroll_left', LEFT);
vimfx.set('mode.normal.scroll_right', RIGHT);
vimfx.set('mode.normal.scroll_to_top', 'gg');
vimfx.set('mode.normal.scroll_to_bottom', 'G');
vimfx.set('mode.normal.follow', 'f');
vimfx.set('mode.normal.follow_in_tab', 'F');
vimfx.set('mode.hints.exit', '<escape>');
vimfx.set('mode.normal.tab_select_previous', LEFT.toUpperCase());
vimfx.set('mode.normal.tab_select_next', RIGHT.toUpperCase());
vimfx.set('mode.normal.tab_close', 'x');
vimfx.set('mode.normal.tab_restore', 'X');
vimfx.set('mode.normal.find', '/');
vimfx.set('mode.normal.find_highlight_all', 'a/');
vimfx.set('mode.normal.find_next', 'l');
vimfx.set('mode.normal.find_previous', 'L');
vimfx.set('mode.find.exit', '<escape>	<enter>');
vimfx.set('mode.normal.esc', '<force><escape>');
vimfx.set('hint_chars', 'aoeuidhtns-');
vimfx.set('blacklist', '*codio.com*');
