;; -*- mode: emacs-lisp -*-

(source gnu)
(source melpa)

;; simplify and organize package setup
(depends-on "use-package")
(depends-on "diminish")
(depends-on "bind-key")

;; tame annoying popup windows
(depends-on "shackle")

;; misc
(depends-on "doom-themes")
